# Generated by Django 5.0.2 on 2024-03-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionSet',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='title',
        ),
    ]
