# Generated by Django 5.0.2 on 2024-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_questions_questionset_rename_id_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='questionsList',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
