# Generated by Django 5.0.2 on 2024-03-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionset_questionslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
        migrations.AlterField(
            model_name='questionset',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
