# Generated by Django 5.0.2 on 2024-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionset_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
    ]
