# Generated by Django 5.0.2 on 2024-03-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionset')),
            ],
        ),
    ]
