# Generated by Django 5.0.2 on 2024-04-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_answerset_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerSet',
            new_name='AnswerList',
        ),
        migrations.RenameModel(
            old_name='QuestionSet',
            new_name='QuestionList',
        ),
        migrations.RenameField(
            model_name='answerlist',
            old_name='answers',
            new_name='answer_list',
        ),
        migrations.RenameField(
            model_name='answerlist',
            old_name='questionSet',
            new_name='question_list',
        ),
        migrations.RenameField(
            model_name='questionlist',
            old_name='questionsList',
            new_name='question_list',
        ),
    ]
