# Generated by Django 5.0.2 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_answerset_answerlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
